#!/bin/bash
mysql -uroot <<MYSQL_SCRIPT
use mysql;
CREATE DATABASE wordpress;
CREATE USER 'kvdanilov'@'localhost' IDENTIFIED BY '3100369';
GRANT ALL PRIVILEGES ON wordpress.* TO 'kvdanilov'@'localhost';
FLUSH PRIVILEGES;
EXIT;
MYSQL_SCRIPT
