#!/bin/bash
mysql -uroot <<MYSQL_SCRIPT
use mysql;
ALTER USER 'root'@'localhost' IDENTIFIED WITH 'caching_sha2_password' BY 'Testpass1$';
CREATE USER repl@'%' IDENTIFIED WITH 'caching_sha2_password' BY 'oTUSlave#2020'; 
GRANT REPLICATION SLAVE ON *.* TO repl@'%';
SHOW MASTER STATUS;
EXIT;
MYSQL_SCRIPT
