#!/bin/bash

echo "Изменяем hostname VM"
hostnamectl set-hostname master #название устройства
systemctl restart systemd-hostnamed #перезапускаем службу
echo "Отключаем Firewall"
systemctl disable firewalld #удаляем из автозагрузки firewalld
systemctl stop firewalld #выключаем firewalld
echo "Устанавливаем другой Firewall"
dnf install -q -y iptables-services #устанавливаем iptables 
cp ./iptables /etc/sysconfig/iptables #копируем требуемые настройки
systemctl restart iptables #рестартуем службу
systemctl enable iptables #добавляем в автозагрузку
echo "Корректируем м сетевые настройки"
cp ./enp0s3.nmconnection /etc/NetworkManager/system-connections #копируем настройки сервера
systemctl restart NetworkManager #рестартуем сетевую службу
echo "Выключение Selinux"
sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config  #изменяем положение селинукс
setenforce 0 #выключаем селинукс
#установка докера
echo "Устанавливаем Docker"
sudo yum install -q -y yum-utils 
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo  #добавляем репозиторий для скачивания
sudo yum install -q -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
systemctl start docker #стартуем докер
systemctl enable docker #добавляем в автозагрузку
echo "Скачиваем образы Prometheus, Grafana, Node-exporter, Mysql"
docker pull -q prom/prometheus #скачивание докер-образа прометеус
docker pull -q grafana/grafana #скачивание докер-образа графаны
docker pull -q prom/node-exporter #скачивание докер-образа node-exporter
docker pull -q mysql/mysql-server:8.0 #скачивание докер-образа mysql-server
unzip -q www.zip
chmod 777 html1 html2 html0
#Устанавливаем NGINX / APACHE
dnf install -q -y nginx httpd
cp -r ./htm* /var/www/  #копируем ресурсы сайтов
#Рестартим докер после изменения настроек фаерволла
systemctl restart docker
echo "Подготовка успешно выполнена"