#!/bin/bash
echo "Устанавливаем Node_exporter"
wget https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-386.tar.gz
tar -xvf node_exporter-1.4.0.linux-386.tar.gz
sudo mv node_exporter-1.4.0.linux-386/node_exporter /usr/local/bin/
sudo useradd -rs /bin/false node_exporter
cp ./node_exporter.service /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl start node_exporter
sudo systemctl enable node_exporter
echo "Устанавливаем Filebeat"
sudo dpkg -i filebeat-8.9.1-amd64.deb
cp ./filebeat.yml /etc/filebeat/filebeat.yml
systemctl restart filebeat.service
sudo filebeat modules enable apache
cp ./apache.yml /etc/filebeat/modules.d/apache.
systemctl restart filebeat.service
