#!/bin/bash

echo "Изменяем hostname VM"
hostnamectl set-hostname wordpress #Hostname VM
systemctl restart systemd-hostnamed #перезапускаем службу
echo "Устанавливаем статический IP адрес"
nmcli connection show
nmcli con add type ethernet con-name 'static-ip' ifname enp0s3 ipv4.method manual ipv4.addresses 192.168.0.108/24 gw4 192.168.0.1
nmcli con mod static-ip ipv4.dns 8.8.8.8
nmcli con up id 'static-ip'
echo "Применяем правила IPTABLES"
bash ./rules.v4
echo "Устанавливаем Apache"
sudo apt install apache2 -y
sudo systemctl enable apache2
echo "Устанавливаем дополнительные расширения для PHP"
sudo apt install -y php php-{common,mysql,xml,xmlrpc,curl,gd,imagick,cli,dev,imap,mbstring,opcache,soap,zip,intl} -y
echo "Устанавливаем Базу данных Mysql"
apt install mysql-server-8.0 -y
cp ./mysqld.cnf /etc/mysql/mysql.conf.d/mysqld.cnf
systemctl restart mysql
systemctl start mysql
echo "Подключемся к Mysql и создаем пользователя для репликации"
sudo mysql
bash ./mysql-master
echo "Скрипт подготовки репликации на master завершен"

